reserved = {
    'if': 'IF',
    'else': 'ELSE',
    'while': 'WHILE',
    'for': 'FOR',
    'new': 'NEW',
    'NewArray': 'NEWARRAY',
    'int': 'INT',
    'interface': 'INTERFACE',
    'bool': 'BOOL',
    'void': 'VOID',
    'return': 'RETURN',
    'break': 'BREAK',
    'class': 'CLASS',
    'double': 'DOUBLE',
    'extends': 'EXTENDS',
    'null': 'NULL',
    'Print': 'PRINT',
    'string': 'STRING',
    'implements': 'IMPLEMENTS',
    'ReadLine': 'READLINE',
    'ReadInteger': 'READInteger',
    'this': 'THIS'
}